image: docker:latest

stages:
  - build
  - release

services:
  - docker:dind

variables:
  ECR_REPOSITORY: 525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing
  CONTAINER_TEST_IMAGE: $ECR_REPOSITORY:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $ECR_REPOSITORY:latest

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region eu-west-1)

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE Moneteer.Landing
    - docker push $CONTAINER_TEST_IMAGE

release:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - redesign