image: docker:latest

stages:
  - build
  - publish

services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - "docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY"

build:
  stage: build
  script:
    - "docker build Moneteer.Landing"

deploy:
  stage: publish
  script:
    - "docker push $IMAGE_TAG"
