image: docker:latest

stages:
  - build
  - release

services:
  - docker:dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE Moneteer.Landing
    - docker push $CONTAINER_TEST_IMAGE

release:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: release
  script:
    
    # - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    # - docker push $CONTAINER_RELEASE_IMAGE
    - docker login --username=_ --password=$HEROKU_AUTH_KEY registry.heroku.com
    - docker pull registry.gitlab.com/cado82/moneteer-landing:latest
    - docker tag registry.gitlab.com/cado82/moneteer-landing:latest registry.heroku.com/moneteer/web
    - docker push registry.heroku.com/moneteer/web
  only:
    - redesign