image: docker:latest

stages:
  - build
  - release

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region eu-west-1)

variables:
  APP_IMAGE_NAME: 525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing/app
  PROXY_IMAGE_NAME: 525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing/proxy

build:
  stage: build
  script:
    - docker build --pull -t $APP_IMAGE_NAME:$CI_COMMIT_SHORT_SHA app/Moneteer.Landing
    - docker build --pull -t $PROXY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA nginx
    - docker push $APP_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $PROXY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA

release:
  stage: release
  script:
    - docker pull $APP_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker pull $PROXY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $APP_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $APP_IMAGE_NAME:latest
    - docker tag $PROXY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $PROXY_IMAGE_NAME:latest
    - docker tag $APP_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $APP_IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker tag $PROXY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $PROXY_IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker push $APP_IMAGE_NAME:latest
    - docker push $PROXY_IMAGE_NAME:latest
    - docker push $APP_IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker push $PROXY_IMAGE_NAME:$CI_COMMIT_REF_NAME
  only:
    - master