image: docker:latest

stages:
  - build
  - release

services:
  - docker:dind

variables:
  APP_IMAGE_NAME: 525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing/app
  PROXY_IMAGE_NAME: 525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing/proxy
  APP_TEST_IMAGE: $APP_IMAGE_NAME:$CI_COMMIT_REF_SLUG
  PROXY_TEST_IMAGE: $PROXY_IMAGE_NAME:$CI_COMMIT_REF_SLUG
  APP_RELEASE_IMAGE: $APP_IMAGE_NAME:latest
  PROXY_RELEASE_IMAGE: $PROXY_IMAGE_NAME:latest

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region eu-west-1)

build:
  stage: build
  script:
    - docker build --pull -t $APP_TEST_IMAGE app
    - docker build --pull -t $PROXY_TEST_IMAGE nginx
    - docker push $APP_TEST_IMAGE
    - docker push $PROXY_TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $APP_TEST_IMAGE
    - docker pull $PROXY_TEST_IMAGE
    - docker tag $APP_TEST_IMAGE $APP_RELEASE_IMAGE
    - docker tag $PROXY_TEST_IMAGE $PROXY_RELEASE_IMAGE
    - docker push $APP_RELEASE_IMAGE
    - docker push $PROXY_RELEASE_IMAGE
  only:
    - master