image: microsoft/dotnet:latest

stages:
  - build
  
before_script:
  - "dotnet restore -s https://www.myget.org/F/dumpster-unicorn-fish/auth/$MYGET_API_KEY/api/v3/index.json -s https://api.nuget.org/v3/index.json"  

build:
  stage: build
  script:
    - "dotnet build Moneteer.Landing --no-restore"
