version: "3"
services:
  app:
    image: "525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing/app:latest"
    ports:
      - "5000:5000"
    environment:
      - OpenIdConnectAuthority=https://identity.moneteer.com
      - CorsAllowedOrigins=https://app.moneteer.com
      - ASPNETCORE_ENVIRONMENT=Production
  proxy:
    image: "525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/landing/proxy:latest"
    ports:
      - "80:80"

# ecs-cli compose -f docker-compose-aws-production.yml service up --target-group-arn arn:aws:elasticloadbalancing:eu-west-1:525140287988:loadbalancer/app/moneteer-landing-load-balancer/ca7056f0e2756371 --container-name proxy --container-port 80 --role ecsServiceRole