version: "3"
services:
  app:
    build:
      context: app/Moneteer.Landing
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"
  proxy:
    build:
      context: nginx/dev
      dockerfile: Dockerfile
    ports:
      - "80:80"